import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Web tutorials",
  description: "Generated by som",
};

export default function RootLayout({ children }) {
  return (
    <html
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <h1><a href="/">WEB</a></h1>

        <ol>
          <li><a href="/read/1">html</a></li>
          <li><a href="/read/2">css</a></li>
    
        </ol>

        {children}

        <ul>
          <li><a href="/create">Create</a></li>
          <li><a href="/update/1">Update</a></li>
          <li><input type="button" value="delete" /></li>        
        </ul>
        
        </body>
    </html>
  );
}

